name: Build and Test
on: [push, pull_request]
jobs:
  build:
    name: Go CI
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Check out source
        uses: actions/checkout@v3
      - name: Build
        run: go build ./...
      - name: Test
        run: |
          go test -v ./...
