name: Build and Test
on: [push, pull_request]
jobs:
  build:
    name: Go CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.0
          check-latest: true
      - name: Test Next
        if: always()
        run: |
          cd app/next
          go mod tidy
          go test -v ./...
      - name: Test v050
        if: always()
        run: |
          cd app/v050
          go mod tidy
          go test -v ./...
      - name: Test v047
        if: always()
        run: |
          cd app/v047
          go mod tidy
          go test -v ./...
