name: Build and Test Next
on:
  pull_request:
    branches:
      - main
  push:
jobs:
  build:
    name: Go CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          check-latest: true
      - name: Test Next
        run: |
          cd app/next
          go mod tidy
          go test -v ./...
