# This job is used to clone the Cosmos SDK SimApp folder used by simapp.zone
name: Refresh SimApp

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *" # Every day at 1am UTC

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          check-latest: true

      - name: update simapp next v2
        if: always()
        run: make update-next-v2

      - name: update simapp next
        if: always()
        run: make update-next

      - name: update simapp v052 v2
        if: always()
        run: make update-v052-v2

      - name: update simapp v052
        if: always()
        run: make update-v052

      - name: update simapp v050
        if: always()
        run: make update-v050

      - name: update simapp v047
        if: always()
        run: make update-v047

      - uses: stefanzweifel/git-auto-commit-action@v5
        if: always()
        with:
          commit_message: sync simapp changes
