name: Build and Test v0.47.x
on:
  pull_request:
    branches:
      - main
  push:
jobs:
  build:
    name: Go CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          check-latest: true
      - name: Test v047
        run: |
          cd app/v047
          go mod tidy
          go test -v ./...
